### Basic opearations in list

In [46]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits.count('apple')#

2

In [47]:
fruits.reverse()
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [48]:
fruits.append('grape')
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']

In [49]:
fruits.sort()
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']

In [50]:
fruits.pop()


'pear'

### another use case

In [63]:
list=["go","python","javascript","ruby"]
list.insert(1,"rust")
print(list)

['go', 'rust', 'python', 'javascript', 'ruby']


In [64]:
list.pop(3)#time for typescript so pop the javascript :d

'javascript'

In [65]:
list.remove("go")
print(list)

['rust', 'python', 'ruby']


# Geeks for geeks python


In [5]:
import numpy as py

a = py.array([[1,2,3,4],[4,55,1,2],
              [8,3,20,19],[11,2,22,21]])
m = py.reshape(a,(4, 4))
print(m)

[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]
 [11  2 22 21]]


### Accessing element

In [2]:
print("\nAccessing Elements")
print(a[1])
print(a[2][0])



Accessing Elements
[ 4 55  1  2]
8


### Adding Element

In [3]:
m = py.append(m,[[1, 15,13,11]],0)
print("\nAdding Element")
print(m)


Adding Element
[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]
 [11  2 22 21]
 [ 1 15 13 11]]


### Deleting Element

In [6]:
m = py.delete(m,[1],0)
print("\nDeleting Element"print(m)


Deleting Element
[[ 1  2  3  4]
 [ 8  3 20 19]
 [11  2 22 21]]


# LİNKED LİST TRAVERSAL

In [8]:
# A simple Python program to introduce a linked list

# Node class
class Node:

    # Function to initialise the node object
    def __init__(self, data):
        self.data = data # Assign data
        self.next = None # Initialize next as null


# Linked List class contains a Node object
class LinkedList:

    # Function to initialize head
    def __init__(self):
        self.head = None


# Code execution starts here
if __name__=='__main__':

    # Start with the empty list
    llist = LinkedList()

    llist.head = Node(1)
    second = Node(2)
    third = Node(3)

    '''
    Three nodes have been created.
    We have references to these three blocks as head,
    second and third

    llist.head     second             third
        |             |                 |
        |             |                 |
    +----+------+     +----+------+     +----+------+
    | 1 | None |     | 2 | None |     | 3 | None |
    +----+------+     +----+------+     +----+------+
    '''

    llist.head.next = second; # Link first node with second

    '''
    Now next of first Node refers to second. So they
    both are linked.

    llist.head     second             third
        |             |                 |
        |             |                 |
    +----+------+     +----+------+     +----+------+
    | 1 | o-------->| 2 | null |     | 3 | null |
    +----+------+     +----+------+     +----+------+
    '''

    second.next = third; # Link second node with the third node

    '''
    Now next of second Node refers to third. So all three
    nodes are linked.

    llist.head     second             third
        |             |                 |
        |             |                 |
    +----+------+     +----+------+     +----+------+
    | 1 | o-------->| 2 | o-------->| 3 | null |
    +----+------+     +----+------+     +----+------+
    '''


In [9]:
# A simple Python program for traversal of a linked list

# Node class
class Node:

    # Function to initialise the node object
    def __init__(self, data):
        self.data = data # Assign data
        self.next = None # Initialize next as null


# Linked List class contains a Node object
class LinkedList:

    # Function to initialize head
    def __init__(self):
        self.head = None

    # This function prints contents of linked list
    # starting from head
    def printList(self):
        temp = self.head
        while (temp):
            print (temp.data)
            temp = temp.next


# Code execution starts here
if __name__=='__main__':

    # Start with the empty list
    llist = LinkedList()

    llist.head = Node(1)
    second = Node(2)
    third = Node(3)

    llist.head.next = second; # Link first node with second
    second.next = third; # Link second node with the third node

    llist.printList()


1
2
3


### Reversed linked list

In [10]:
# Iterative Python program to reverse a linked list
class Node:
    def __init__(self, new_data):
        self.data = new_data
        self.next = None

# Given the head of a list, reverse the list and return the
# head of reversed list
def reverse_list(head):

    # Initialize three pointers: curr, prev and next
    curr = head
    prev = None

    # Traverse all the nodes of Linked List
    while curr is not None:

        # Store next
        next_node = curr.next

        # Reverse current node's next pointer
        curr.next = prev

        # Move pointers one position ahead
        prev = curr
        curr = next_node

    # Return the head of reversed linked list
    return prev

def print_list(node):
    while node is not None:
        print(f" {node.data}", end="")
        node = node.next
    print()

if __name__ == "__main__":
    ''' Create a hard-coded linked list:
     1 -> 2 -> 3 -> 4 -> 5 '''

    head = Node(1)
    head.next = Node(2)
    head.next.next = Node(3)
    head.next.next.next = Node(4)
    head.next.next.next.next = Node(5)

    print("Given Linked list:", end="")
    print_list(head)

    head = reverse_list(head)

    print("Reversed Linked List:", end="")
    print_list(head)


Given Linked list: 1 2 3 4 5
Reversed Linked List: 5 4 3 2 1


# A * Search Algorithm in Python


In [11]:
from queue import PriorityQueue

# A class to represent a node in the grid
class Node:
    def __init__(self, parent=None, position=None):
        self.parent = parent
        self.position = position

        self.g = 0  # Distance from start node
        self.h = 0  # Heuristic - estimated distance from current node to end node
        self.f = 0  # Total cost

    def __eq__(self, other):
        return self.position == other.position

# A* search algorithm
def astar(maze, start, end):
    # Create start and end node
    start_node = Node(None, start)
    end_node = Node(None, end)

    # Initialize both open and closed lists
    open_list = PriorityQueue()
    open_list.put((0, start_node))  # (f, node)
    closed_list = set()

    while not open_list.empty():
        _, current_node = open_list.get()
        closed_list.add(current_node.position)

        # If the end is reached, reconstruct the path
        if current_node == end_node:
            path = []
            while current_node is not None:
                path.append(current_node.position)
                current_node = current_node.parent
            return path[::-1]  # Return reversed path

        # Generate children
        children = []
        for new_position in [(0, -1), (0, 1), (-1, 0), (1, 0)]:  # Adjacent squares (left, right, up, down)
            node_position = (current_node.position[0] + new_position[0],
                             current_node.position[1] + new_position[1])

            # Make sure within range and walkable (i.e., not a wall)
            if (0 <= node_position[0] < len(maze) and
                    0 <= node_position[1] < len(maze[0]) and
                    maze[node_position[0]][node_position[1]] == 0):

                new_node = Node(current_node, node_position)
                children.append(new_node)

        # Loop through children
        for child in children:
            if child.position in closed_list:
                continue

            # Calculate the f, g, and h values
            child.g = current_node.g + 1
            child.h = ((child.position[0] - end_node.position[0]) ** 2 +
                       (child.position[1] - end_node.position[1]) ** 2)
            child.f = child.g + child.h

            # If child is already in open list with a higher cost, skip it
            if any(open_child[1].position == child.position and open_child[1].f <= child.f for open_child in open_list.queue):
                continue

            # Add the child to the open list
            open_list.put((child.f, child))

    return None  # No path found

# Example usage
maze = [
    [0, 1, 0, 0, 0],
    [0, 1, 0, 1, 0],
    [0, 0, 0, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0]
]

start = (0, 0)
end = (4, 4)

path = astar(maze, start, end)
print("Path found:", path)


Path found: [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4)]
